### ISSUE TITLE
When a page render over one tree, only the first tree can zoom、move、etc...

### ISSUE THREAD

**Issue by elowes** [bkrem/react-d3-tree#100]
## Are you reporting a bug, or opening a feature request?
bug

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?
[reprocuce link](https://codesandbox.io/s/88qlo431p9)
> you can try to move the second tree in the page. then you will find that doesn't work.

## What version of react-d3-tree are you using?
latest

**Comment by bkrem** [comment]
Fixed in [v1.10.5](https://github.com/bkrem/react-d3-tree/releases/tag/v1.10.5) 🎉

**Comment by tinaClin** [comment]
This issue is occurred again in v2.0.0 ....

**Comment by bkrem** [comment]
Yes good catch, this was a silly regression I caused during the v2 refactor. Thank you for making me aware of this @tinaClin 🙏 

Fixed in [v2.0.1](https://github.com/bkrem/react-d3-tree/releases/tag/v2.0.1) 🚀 

Please comment here again if the issue persists for any reason.
