### ISSUE TITLE
Question: Is there any way to make lines to go to center

### ISSUE THREAD

**Issue by ktjd123** [bkrem/react-d3-tree#109]
![2018-06-21 6 10 41](https://user-images.githubusercontent.com/15044488/41709575-7b579226-757e-11e8-9c9f-80739a5fbd45.png)
my current react-d3-tree looks like this

is there any way to make lines to center? like

![kakaotalk_photo_2018-06-21-18-10-55](https://user-images.githubusercontent.com/15044488/41709601-8daf8708-757e-11e8-97d8-2609c5cba5b8.png)

always thank you and appreciate your works

**Comment by ktjd123** [comment]
@bkrem can you check this for me ?? Thank you

**Comment by ktjd123** [comment]
@bkrem can you check this for me please??

**Comment by bkrem** [comment]
Hey @ktjd123,

It's not entirely clear to me what's going on here, it looks like you're trying to use a horizontal graph that has a root node + 2 siblings (but no children) in a vertical way from the screenshots, even though you'd want a vertical graph with 2 parent-child relationships.

I'm happy to help but you have to meet me half way with a reproduction case (https://codesandbox.io/) or details of your configuration. Screenshots alone give me no context as to what is going on.

**Comment by ktjd123** [comment]
Thank you for reply and feedback to my comment!! I felt I was wrong about how to send my opinion thank you for making me know the right way

![-1](https://user-images.githubusercontent.com/15044488/42049060-cc164ed4-7b3f-11e8-8fb4-8f6c3d0bd14c.png)
The final shape I wanted to make is this shape. Everything is at center ( text, line, rect) 

So i tried to make it with nodeSvgShape with shape: "rect"
And this is what happend [https://codesandbox.io/s/jjww36ly13](url)

Then I tried to move a little bit with widht, height, x, y options
This is the result [https://codesandbox.io/s/6lx875m6kr](url)

I found out in this way I can't make what I want.

Is there any way to make this??

Always Thank you and appreciate your work @bkrem

**Comment by bkrem** [comment]
Thanks for posting the reproduction, seeing your configuration made it a lot easier to help with this.

I think this is the layout you're looking for @ktjd123: https://codesandbox.io/s/zxnx9m92wp

Only two things I changed:
* In `shapeProps` I set the negative `x` and `y` offsets to (approximately) half the shape's `width` and `height`
* Specified the `textLayout` prop with `{textAnchor: 'middle'}`

Hope that helps! :)

**Comment by ktjd123** [comment]
Thank you!! It really helped me!!!
