### ISSUE TITLE
foreignobject width not equal to nodeSize.x

### ISSUE THREAD

**Issue by murphyke** [bkrem/react-d3-tree#120]
## Are you reporting a bug, or opening a feature request?

Asking a question about possible bug in docs or other.
  
## What is the actual behavior/output?

A `nodeWidth.x` of 200 yields a `<foreignobject>` width of 176.  A value of 140 yields a width of 116. The difference is always 24. The `height` is also 24 less than `y`. I'm not attempting to control the width of `<foreignobject>`, i.e. I'm using:

```
                nodeLabelComponent={{
                  render: <NodeLabel/>,
                  foreignObjectWrapper: {
                    y: 2,
                    x: 5,
                  }
                }}
```

## What is the behavior/output you expect?

The README states "foreignObjectWrapper will set its width and height attributes to whatever values nodeSize.x and nodeSize.y return by default".

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?

I can do this if I have to.

## What version of react-d3-tree are you using?

1.10.6

**Comment by bkrem** [comment]
Hi @murphyke,

Thanks for pointing this out, I totally overlooked that this behaviour hadn't been properly documented. 

Your observation is correct, by default the `width/height` properties on `foreignObject` are evaluated as `nodeSize.x - BASE_MARGIN` & `nodeSize.y - BASE_MARGIN`, where `BASE_MARGIN` is 24px.

I corrected the docs to reflect the default behaviour. If people find this more of a nuisance than a useful default I'm happy to deprecate it in a future release.
