### ISSUE TITLE
Specific error on improper data input

### ISSUE THREAD

**Issue by alex0112** [bkrem/react-d3-tree#145]
## Are you reporting a bug, or opening a feature request?
Feature request/New Behavior
  
## What is the actual behavior/output?
This module expects a json string that is an _array of one object_:
```
const data = [
    {
    name: 'Top Level',
    children: [
      {
        name: 'Level 2: A'
      },
      {
        name: 'Level 2: B'
      },
    ]
    },
];
```

But I would often forget and pass the function _an object instead_:
```
const data =     {
    name: 'Top Level',
    children: [
      {
        name: 'Level 2: A'
      },
      {
        name: 'Level 2: B'
      },
    ]
};
```

Which throws an error:

### _TypeError: e.map is not a function_
`// node_modules/react-d3-tree/lib/react-d3-tree.min.js:1`
> 1 | !function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(require("react"),require("prop-types"),require("d3"),require("uuid"),require("clone"),require("deep-equal"),require("react-transition-group")):"function"==typeof define&&define.amd?define("react-d3-tree",["react","prop-types","d3","uuid","clone","deep-equal","react-transition-group"],t):"object"==typeof exports?exports["react-d3-tree"]=t(require("react"),require("prop-types"),require("d3"),require("uuid"),require("clone"),require("deep-equal"),require("react-transition-group")):e["react-d3-tree"]=t(e.react,e["prop-types"],e.d3,e.uuid,e.clone,e["deep-equal"],e["react-transition-group"])}(this,function(e,t,n,r,o,a,i){return function(e){function t(r){if(n[r])return n[r].exports;var o=n[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,t),o.l=!0,o.exports}var n={};return t.m=e,t.c=n,t.d=function(e,n,r){t.o(e,n)||Object.defineProperty(e,n,{configurable:!1,enumerable:!0,get:r})},t.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(n,"a",n),n},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="",t(t.s=6)}([function(t,n){t.exports=e},function(e,n){e.exports=t},function(e,t){e.exports=n},function(e,t){e.exports=r},function(e,t){function n(e,t){var n=e[1]||"",o=e[3];if(!o)return n;if(t&&"function"==typeof btoa){var a=r(o);return[n].concat(o.sources.map(function(e){return"/*# sourceURL="+o.sourceRoot+e+" */"})).concat([a]).join("\n")}return[n].join("\n")}function r(e){return"/*# sourceMappingURL=data:application/json;charset=utf-8;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(e))))+" */"}e.exports=function(e){var t=[];return t.toString=function(){return this.map(function(t){var r=n(t,e);return t[2]?"@media "+t[2]+"{"+r+"}":r}).join("")},t.i=function(e,n){"string"==typeof e&&(e=[[null,e,""]]);for(var r={},o=0;o<this.length;o++){var a=this[o][0];"number"==typeof a&&(r[a]=!0)}for(o=0;o<e.length;o++){var i=e[o];"number"==typeof i[0]&&r[i[0]]||(n&&!i[2]?i[2]=n:n&&(i[2]="("+i[2]+") and ("+n+")"),t.push(i))}},t}},function(e,t,n){function r(e,t){for(var n=0;n<e.length;n++){var `

## What is the behavior/output you expect?
IMHO a less verbose and more specific error saying something about what's causing the issue would be helpful, especially to new users of the module who aren't yet familiar with what input is expected. 
Something like:
`Error: Expected data to be in the form <EXAMPLE>`
(I'm open to suggestions on what the error should say)

## What version of react-d3-tree are you using?
1.10.6

**Comment by bkrem** [comment]
Hey @alex0112,

Yup totally agree that this is not helpful.

There are really two initial design decisions at play here that I regret and need fixing:
* The input type should simply be the root node (i.e. just the object without the redundant array around it)
* The bundle shouldn't be minified by default to make stack traces useful.

Both of these are breaking changes so they need to be part of v2 but they're on my list for being addressed.

In the meantime I will aim to add a more helpful error message for the next v1.x release to avoid confusion.

**Comment by bkrem** [comment]
This should no longer be an issue in [v1.12.0](https://github.com/bkrem/react-d3-tree/releases/tag/v1.12.0), you can now simply pass the root node object directly if you prefer.
