### ISSUE TITLE
[Question] Re-centering tree in div on clicking a node

### ISSUE THREAD

**Issue by amad-person** [bkrem/react-d3-tree#151]
I'm using the CenteredTree recipe to render the tree in the center of the parent div on the initial render.

I wanted to know if it is possible to scale and re-center the rendered tree inside its parent component _every time a node is expanded_?

**Comment by bkrem** [comment]
Hi @amad-person,

No this unfortunately isn't part of the feature set at the moment since the `translate` & `zoom` props are intended to set up the graph in a useful position for the user and letting them move freely from that point onwards.

An `autoScale` prop would definitely be cool to have, although on a graph of significant size the nodes would quickly become almost unclickable due to them becoming very small as the graph auto-scales.

**Comment by amad-person** [comment]
That makes sense, thanks @bkrem!

**Comment by bkrem** [comment]
No problem, sorry I can't help much right now for your use case. 

I'm going to leave this open for further discussion since someone else may have a good approach for this.

**Comment by mwilde345** [comment]
Couple thoughts:
* use onclick event, get click x and y, modify graph transform based on some factor of those values
  * ```ReactDOM.findDOMNode(this).firstChild.firstChild.firstChild.setAttribute('transform', `translate(${someX},${someY}) scale(0.7)`);```
* Store an object that tracks the nodes' coordinates in the container, according to their 'id'. Updates would be expensive
* When a node component mounts, add its x and y values to the actual node data object. Update the entire data object (very expensive)

**Comment by mwilde345** [comment]
@bkrem If i update the state.translate property after the graph is rendered, it is not re-rendered with the new values. Where is this in the code?

**Comment by david-saint** [comment]
Hi what's the CenteredTree recipe?

**Comment by npetzall** [comment]
@mwilde345 I was actually looking into this and the prop seems to be set, but react doesn't seem to re-render it.

So I did some fiddling, I've done react for a cpl of weeks, so I might be waaay off on the solution. I added a key to the g component rendered by NodeWrapper. The key was just translate.x, translate.y+scale as a string. This caused the g component to re-render when translate was set.

**Comment by franklx2** [comment]
like @npetzall noted above, updating the HTML attribute for `transform=translate(x,y)` directly doesn't affect the <Tree> component's _translate_ state. Once you drag the canvas, the component resumes updating _translate_ again. I was updating the position of the tree by manually updating the first 'g' as you were, however, to get around the jumpiness behavior I've just gone with updating _this.state.translate_:

`this.state.translate = 
    {
      x: applied.x,
      y: applied.y
    }`

I don't know how to do smooth transitions with this approach, however. I might just forgo it

**Comment by bkrem** [comment]
This has been implemented via #381 and shipped as part of https://github.com/bkrem/react-d3-tree/releases/tag/v3.3.0 🚀 

Closing.

**Comment by bkrem** [comment]
### Update

https://github.com/bkrem/react-d3-tree/releases/tag/v3.3.1 ships a fix for a calculation bug when centering nodes via `dimensions` in `horizontal` orientation. 

**Please update to `v3.3.1` instead if you want to use this feature.**
