### ISSUE TITLE
render React component in a node

### ISSUE THREAD

**Issue by sibelius** [bkrem/react-d3-tree#158]
can we render a custom react component in any node?

**Comment by alex0112** [comment]
From the README:

<img width="955" alt="screen shot 2018-11-17 at 9 50 33 am" src="https://user-images.githubusercontent.com/7142972/48663490-46bde980-ea4e-11e8-9138-ad1084b63ce1.png">

**Comment by sibelius** [comment]
tks, I'll check it out
