### ISSUE TITLE
Simplify `parse[FileType]` methods & allow specifying parent/child field names

### ISSUE THREAD

**Issue by bkrem** [bkrem/react-d3-tree#16]
Use an options object (i.e. `parse[FileType](fileName, opts)` signature) rather than individual parameters to simplify setting parse configs for specific file + provide extensibility.

- [ ] Implementation
- [ ] Unit test
- [ ] Docs

**Comment by akapei** [comment]
@bkrem Any update on this feature or on v2? Happy to contribute if I can.
