### ISSUE TITLE
Allow customizeable context-menu on node right-clicks

### ISSUE THREAD

**Issue by pdguru81** [bkrem/react-d3-tree#174]
Thank you for taking the time to report an issue with react-d3-tree!  

Feel free to delete any questions that do not apply.

## Are you reporting a bug, or opening a feature request?
New feature request
  
## What is the actual behavior/output?
Right now, right-clicks are not processed as events by this node.

## What is the behavior/output you expect?
A customizable context-menu should be displayed on a node when a user right-clicks on any node.

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?
Yes

## What version of react-d3-tree are you using?
version 1.12.1, which I believe is the latest

## If react-d3-tree crashed with a traceback, please paste the full traceback below.
[Replace with your traceback]

**Comment by bkrem** [comment]
Hi @pdguru81,

This is definitely a cool idea but unfortunately out-of-scope given the already limited amount of time I have to work on the library + pushing for `v2.x` to get done.

If you (or somebody else) implement(s) this in a stable way I'm happy to get it released, but this is too large a feature for me to implement and then maintain forever without knowing whether it see significant interest.
