### ISSUE TITLE
Using a svg image for the node image

### ISSUE THREAD

**Issue by Robert-Fish** [bkrem/react-d3-tree#182]
How am i able to use a svg image for the node image?

**Comment by bkrem** [comment]
Hi @Robert-Fish,

By node image I'm going to assume you mean the node itself (i.e. an SVG `circle` by default). 
Changing that to an arbitrary SVG element isn't currently possible, but you should be able to **render whatever you like for the node's label element** by using the `nodeLabelComponent` prop and setting the `allowForeignObjects` prop flag.

`v1.x` is opinionated in terms of what is customizable and by how much, `v2.x` (which is currently WIP) is going to be significantly more agnostic in terms of what can be passed to `Node`/`Link` elements.

Sorry for the lack of immediate options here, going to close for now but feel free to reopen if something is unclear.

**Comment by sagar270690** [comment]
Since `image` is also an SVG component, you can just pass 

> `nodeSvgShape={
                        {
                            shape: 'image',
                            shapeProps: {
                                href="https://mdn.mozillademos.org/files/6457/mdn_logo_only_color.png",
                                width: 40,
                                height: 40,
                            }
                        }
                    }`
