### ISSUE TITLE
Implement onClick hook

### ISSUE THREAD

**Issue by bkrem** [bkrem/react-d3-tree#19]
Currently it isn't possible to specify a handler at the `<Tree />` level for node `onClick` events.

- [x] Implementation
- [x] Unit test
- [x] Docs

**Comment by Suzanna-Manoj-Williams** [comment]
Can we get the metadata of the node clicked?

**Comment by bkrem** [comment]
Hi Suzanna,

Can definitely push this as `1.3.1`, what exactly do you define as metadata in this case?

**Comment by Suzanna-Manoj-Williams** [comment]
Hi,
All the nodes should be able to contain the metadata related like id, label etc. So on click, all these data should be accessible on the callback.

eg: children:[
       {
          name: "child1",
          metadata: {
               id: 1
          }
]

So if we click on this node, I should receive, {name: child1, id: 1}

**Comment by Suzanna-Manoj-Williams** [comment]
Is it possible to release with this requirement today? I need this kinda urgent. Thank you.

**Comment by bkrem** [comment]
I'm currently at work but I will try to fit it in afterwards :) 

In the meantime feel free to add a pull request with your suggested changes if it's urgent for you.

**Comment by bkrem** [comment]
@Suzanna-Manoj-Williams 

Published `1.3.1`, onClick handler now passes `nodeData` as the first param of the callback function.
