### ISSUE TITLE
Leaf nodes should not overlap on each other.

### ISSUE THREAD

**Issue by Suzanna-Manoj-Williams** [bkrem/react-d3-tree#20]
Css is messed up when the leaf node label is long, the leaf nodes overlap

- [ ] Implementation
- [ ] Unit test
- [ ] Docs

**Comment by bkrem** [comment]
This unfortunately can't be avoided by default for any arbitrary dataset.
The `nodeSize` and `separation` props can be used to avoid label collisions for now. If that still doesn't work please copy/paste a your dataset here for me to reproduce the issue.
