### ISSUE TITLE
Add prop for colour transforms based on node depth

### ISSUE THREAD

**Issue by bkrem** [bkrem/react-d3-tree#23]
- [ ] Implementation
- [ ] Unit test
- [ ] Docs

**Comment by ryuken** [comment]
does this mean that you can color a specific node?
i.e. you have 3 circles with colors red, blue, yellow
   -
-    -

**Comment by bkrem** [comment]
Hi @ryuken,

Yes that's the main idea 😄 

Ideally I'd like to let the user provide a gradient, e.g. that the nodes get lighter/darker as depth increases, or that they transition from one colour to another.

But the first iteration will be a simple step-wise definition for colour by depth, something like:

```
<Tree 
    ...
     colorByDepth={['green', 'blue', '#fff', '#000',...]}
/>
```

where `green` is applied to all nodes @ depth 1, `blue` @ depth 2...etc


I'm super busy at the moment so I don't have much time to work on this unfortunately. 
If you think you have a good way of implementing the above or something even better, feel free to put in a PR!
