### ISSUE TITLE
onClick is ignored if collapsible prop is false

### ISSUE THREAD

**Issue by justinsisley** [bkrem/react-d3-tree#24]
- [X] Implementation
- [x] Unit test
- [x] ~~Docs~~ (unchanged)

In _/src/Tree/index.js_, line 187, the `handleNodeToggle` method only calls the `handleOnClickCb` method if `this.props.collapsible` is true.

I don't think it makes sense to make the `onClick` prop dependent on using the `collapsible` prop.

**Comment by justinsisley** [comment]
Fix may look something like:

```javascript
handleNodeToggle(nodeId) {
    const matches = this.findNodesById(nodeId, data, []);
    const targetNode = matches[0];
    
    if (this.props.collapsible) {
      const data = clone(this.state.data);
      targetNode._collapsed
        ? this.expandNode(targetNode)
        : this.collapseNode(targetNode);
      this.setState({ data }, () => this.handleOnClickCb(targetNode));
    } else {
      this.handleOnClickCb(targetNode);
    }
  }
```

What do you think?

**Comment by bkrem** [comment]
Hi Justin, yes you're absolutely right it doesn't really make sense to exclude non-collapsible trees from handling onClick events, I was clearly too tired when I added that prop!

PR looking good, going to check over it and then merge if we're all good 👍
