### ISSUE TITLE
initialDepth is not working

### ISSUE THREAD

**Issue by Imadra** [bkrem/react-d3-tree#257]
So, what I'm trying to do is to set initialDepth for my tree like this:
`<Tree data={self.state.data} separation={self.state.separation} pathFunc="elbow" translate={self.state.translate} orientation="vertical" initialDepth={1}/>`
However, my tree is not collapsing to initial depth, so I wonder why is that happening?

## Are you reporting a bug, or opening a feature request?
Bug
  
## What is the actual behavior/output?
Tree is not collapsing to initial depth

## What is the behavior/output you expect?
Tree has to be collapsed

## What version of react-d3-tree are you using?
1.16.1

**Comment by bkrem** [comment]
Hi @Imadra,

I just double checked and `initialDepth` hasn't regressed in terms of what it actually is supposed to do (set the depth on the first render), but I believe you're talking about the case where `initialDepth` is not applied when the data set changes dynamically.

There's already an issue for that case here (#47), so I'll close this as a duplicate.

I'm currently in the process of addressing the issue, so bear with me please; I should be able to finally ship a fix for this very soon :)
