### ISSUE TITLE
initial depth and collaplseneighbouring node not working

### ISSUE THREAD

**Issue by shubham348** [bkrem/react-d3-tree#258]
Thank you for taking the time to report an issue with react-d3-tree!  

Feel free to delete any questions that do not apply.

## Are you reporting a bug, or opening a feature request?
bug
  
## What is the actual behavior/output?
should render initial depth provided and should collapse neighboring nodes
## What is the behavior/output you expect?
[Replace with your answer if relevant]

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?
[Replace with your answer if relevant]

## What version of react-d3-tree are you using?
[Replace with your answer]

## If react-d3-tree crashed with a traceback, please paste the full traceback below.
[Replace with your traceback]

**Comment by bkrem** [comment]
Looks like this duplicates #47 (please reopen with a more detailed description if that's not accurate). 

I'm currently in the process of addressing this, please see the canonical issue above for details :)
