### ISSUE TITLE
Nodes render below links (Z axis)

### ISSUE THREAD

**Issue by justinsisley** [bkrem/react-d3-tree#26]
- [X] Implementation
- [ ] Unit test
- [ ] Docs

Due to the order of rendering nodes before links in `/src/Tree/index.js` (line ~282), nodes appear below links. This can be verified by setting the node color to a light color, and leaving the link color its default black.

I'm making an assumption on this, but I would think most users would prefer the links to appear as though they are passing underneath (or through) nodes, and not passing above them.

**Comment by justinsisley** [comment]
Reverted fix, as this will collide with my other PR. I should have made my previous PR on a branch.

**Comment by bkrem** [comment]
Agreed, it looks as you'd expect this way; haven't been able to commit much time to working on styling/appearance so this will be a welcome PR 🚀

**Comment by justinsisley** [comment]
I'll jump on this now.
