### ISSUE TITLE
Centering tree perspective on a specific node

### ISSUE THREAD

**Issue by julientregoat** [bkrem/react-d3-tree#273]
Hi! Thanks for your work on this package @bkrem , I've been enjoying working with it.

One question I couldn't find an answer to in other issues. most of the questions I read were about centering a tree inside a `div`. I'm looking to move the 'focus' / 'perspective' (not sure of the d3 terminology) to a selected node after click. e.g. the tree stays where it is as far as the DOM is concerned, but the graph is centered around a specific node in the tree.

is there a way to do this with your library?

thanks in advance!

**Comment by julientregoat** [comment]
looks like I misunderstood the `translate` property - that seems like the intended solution here!

**Comment by carmenkolohe** [comment]
Hello! I am so happy to hear you were able to find the solution for this! I am having the same issue, I would like the recenter the tree to a specific node onClick. I understand that I need to use the translate property but, I am unsure of how to generate the correct x and y values. I appreciate any knowledge you share! Thank you!
