### ISSUE TITLE
hi,how can i get a right-to-left tree?

### ISSUE THREAD

**Issue by xyywp** [bkrem/react-d3-tree#281]
Thank you for taking the time to report an issue with react-d3-tree!  

Feel free to delete any questions that do not apply.

## Are you reporting a bug, or opening a feature request?
[Replace with your answer]
  
## What is the actual behavior/output?
[Replace with your answer if relevant]

## What is the behavior/output you expect?
[Replace with your answer if relevant]

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?
[Replace with your answer if relevant]

## What version of react-d3-tree are you using?
[Replace with your answer]

## If react-d3-tree crashed with a traceback, please paste the full traceback below.
[Replace with your traceback]

**Comment by mderanek** [comment]
making depthFactor negative will reverse the direction of your tree

**Comment by xyywp** [comment]
it works, thank you

**Comment by bkrem** [comment]
Thanks for replying to this already @mderanek 🙇 Closing.

**Comment by husainshabbir** [comment]
This works perfectly for a tree with horizontal orientation. How can get the same result for a tree with a vertical orientation? I am trying to get the horizontal tree to expand from right to left (instead of the default left to right).
