### ISSUE TITLE
Disappeared node with fill attribute 

### ISSUE THREAD

**Issue by caginbektas** [bkrem/react-d3-tree#282]
## Are you reporting a bug, or opening a feature request?
Question
  
## What is the actual behavior/output?
3.jpg as attached below

## What version of react-d3-tree are you using?
Latest

Hello,
I have created a tree as you can see below. With that combination, circle nodes are disappearing if you want to use fill as a shapeProps. Could you please have a look and help with that? If you need more information, please ask, I will provide as soon as possible.

I am so appreciated with that, you make a really good work here. Thanks!

## Tree structure
![2](https://user-images.githubusercontent.com/25220107/76093560-74bb9a00-5fc1-11ea-9f5b-63484ca4373d.png)
## Data
![1](https://user-images.githubusercontent.com/25220107/76093561-75ecc700-5fc1-11ea-96eb-546569829dbc.png)
## Output
![3](https://user-images.githubusercontent.com/25220107/76093556-738a6d00-5fc1-11ea-8670-f2fb3f941eab.png)

**Comment by bkrem** [comment]
Hi @caginbektas,

So from the screenshots what I believe is happening here is that you're missing the `shape` property for `ParentNode`. If you set `shape: "circle"` and set a radius for it (e.g. `r: 10`) the node should appear correctly, see the `myTreeData` example here:

https://codesandbox.io/s/dawn-leftpad-mjq69

I just noticed that this is from the example in the docs, my apologies for the confusion. Going to update that example now too.
