### ISSUE TITLE
Configure distance between tree levels

### ISSUE THREAD

**Issue by noahhai** [bkrem/react-d3-tree#287]
Thank you for taking the time to report an issue with react-d3-tree!  

Feel free to delete any questions that do not apply.

## Are you reporting a bug, or opening a feature request?
Feature request
  
## What is the actual behavior/output?
Does not appear to be a way for the tree to adjust distance between levels.

## What is the behavior/output you expect?
Would like to be able to change the distance between levels. E.g. am using a horizontal tree and have some long node names/attributes. They overflow onto the next level. Solution I'd like to do is utilize foreign objects for the node labels, and also increase the distance between the tree's levels.

## What version of react-d3-tree are you using?
1.16.1

**Comment by noahhai** [comment]
figured out it's nodeSize.x

**Comment by OsmarJoseph** [comment]
Hi @noahhai, you increased the node distance based on the labels?
