### ISSUE TITLE
Can i change the length of the lines? there are too short so the graph is not clear

### ISSUE THREAD

**Issue by Houdakilani996** [bkrem/react-d3-tree#309]

**Comment by lluistfc** [comment]
I don't think you can change the length, but you can change the distance at wich the child nodes are placed with `depthFactor`

**Comment by bkrem** [comment]
Apologies for the delay in response here. I wasn't able to work on open source for most of 2020 for both professional and personal reasons, but I'm currently working through the open issue backlog for this library now that v2 has been released.

Thank you for helping out here already @lluistfc 🙏

You can adjust the distance between:
-  **different levels/depths of the tree** by using the [`depthFactor` prop](https://bkrem.github.io/react-d3-tree/docs/interfaces/_tree_types_.treeprops.html#depthfactor).
- **sibling and/or non-sibling nodes at the same depth** by using the [`separation` prop](https://bkrem.github.io/react-d3-tree/docs/interfaces/_tree_types_.treeprops.html#separation).
