### ISSUE TITLE
Duplicated nodes

### ISSUE THREAD

**Issue by airenzp** [bkrem/react-d3-tree#313]
Hi. I wonder if it is possible not to have duplicated nodes if they are the same object in the data, but referenced from different parents. Like adding a link to an existing node instead of painting the subtree again. 
Thanks a lot for your support

**Comment by bkrem** [comment]
Hi @airenzp,

Apologies for the delay in response here. I wasn't able to work on open source for most of 2020 for both professional and personal reasons, but I'm currently working through the open issue backlog for this library now that v2 has been released.

No unfortunately this isn't possible. This package is essentially a set of bindings to the underlying `d3.tree()` implementation, which consumes a JSON data structure. 
JSON does not allow for the type of self-referential links/pointers you suggested here, so this type of optimisation isn't possible as far as I'm aware.
