### ISSUE TITLE
Feature Request: Use Name as Text Node

### ISSUE THREAD

**Issue by jhcccc** [bkrem/react-d3-tree#318]
## Are you reporting a bug, or opening a feature request?
Feature Request
## What is the actual behavior/output?
![image](https://user-images.githubusercontent.com/8275280/90118808-5b4a2580-dd8b-11ea-9cfc-0f18db914031.png)

## What is the behavior/output you expect?
the names are **at the position the nodes**. Instead of **beside the nodes**
![image](https://user-images.githubusercontent.com/8275280/90118909-7cab1180-dd8b-11ea-99f4-07531a9f5104.png)

## What version of react-d3-tree are you using?
1.16.1 (lastest)

**Comment by jhcccc** [comment]
There's a file `https://github.com/bkrem/react-d3-tree/blob/master/src/Node/SvgTextElement.js`, not sure if it's related

**Comment by franklx2** [comment]
Isn't what you're looking for supported by nodeLabelComponent? https://github.com/bkrem/react-d3-tree#nodelabelcomponent

**Comment by jhcccc** [comment]
> Isn't what you're looking for supported by nodeLabelComponent? https://github.com/bkrem/react-d3-tree#nodelabelcomponent

Thanks, this worked fine!
