### ISSUE TITLE
Support flexbox arrangement for node labels/contents

### ISSUE THREAD

**Issue by bkrem** [bkrem/react-d3-tree#32]
- [ ] Implementation
- [ ] Unit test
- [ ] Docs

Being able to arrange the labels of each node in a flexbox-like way would make layouts more consistent and less frustrating when node labels vary strongly in length.

https://github.com/dlmanning/react-flexbox-svg
http://blog.scottlogic.com/2015/02/02/svg-layout-flexbox.html

**Comment by murphyke** [comment]
@bkrem Just for the record, can you briefly describe the reason for closing this issue? Is `nodeLabelComponent` the answer? I just encountered the need to deal with long attribute values in a reasonable way ....
