### ISSUE TITLE
[DOC][BUG]- Styling example uses {sourceNode, targetNode} 

### ISSUE THREAD

**Issue by technicallynick** [bkrem/react-d3-tree#331]
## Are you reporting a bug, or opening a feature request?
Document Bug
  
The section discussing "Styling Links" uses the following function as an example of dynamic class application: 

```javascript
const getDynamicPathClass = ({ sourceNode, targetNode }, orientation) => {
    if (!targetNode.children) {
      // Node has no children -> this link leads to a leaf node.
      return 'link__to-leaf';
    }

    // Style it as a link connecting two branch nodes by default.
    return 'link__to-branch';
  };
```

However, the keys in the first parameter are actually `source` and `target`, so the above example would fail.

**Comment by bkrem** [comment]
Great catch, this clearly slipped by me in the full rewrite of the docs. Thank you @technicallynick 🙏 

Fixed. 

If catch something else that's clearly wrong in the docs, feel free to open a PR so we can have you listed as a contributor for your contributions! :)
