### ISSUE TITLE
Question: is it possible to zoom programmatically?

### ISSUE THREAD

**Issue by awcot** [bkrem/react-d3-tree#332]
The [d3 zoom docs](https://github.com/d3/d3-zoom#zoom_transform) says we can zoom programmatically using `zoom.transform` on a given selection. Is this possible with the current implementation of `bindZoomListener`? Here's what I've done in my app component where a `Tree` is rendered:
```
// Select mounted SVG in an effect
const [svg, setSvg] = useState(undefined)

useEffect(() => {
  setSvg(select('.rd3t-svg'))
}, [])

// Define a function to smoothly translate back to (0, 0)
const resetZoom = () => {
  svg.transition().duration(750).call(d3zoom().transform, zoomIdentity.translate(0, 0).scale(1))
}

return (
  <Tree ...
  ...
  <button onClick={resetZoom}>Reset Zoom</button>
```
After clicking the button, the position *will* reset, but only after the next zoom/drag. There's also no transition. Apologies if this is beyond the scope of the component!

**Comment by ericbowden** [comment]
Any update, did is it possible with react-d3-tree?
