### ISSUE TITLE
Support for `2 dimensional tree structure`

### ISSUE THREAD

**Issue by sajus** [bkrem/react-d3-tree#336]
Thank you for taking the time to report an issue with react-d3-tree!  

Feel free to delete any questions that do not apply.

## Are you reporting a bug, or opening a feature request?
This seems to be bug for me, D3 actually supports `2 dimensional tree structure` where we can have right and left tree together in a single DOM.
  
## What is the actual behavior/output?
Currently we have just one root and right side growth only. 

## What is the behavior/output you expect?
We need to have ability to grow on both left and right side of the root node. 

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?
This is always reproducible, let me know if you need a codepen? 

## What version of react-d3-tree are you using?
latest one.

## If react-d3-tree crashed with a traceback, please paste the full traceback below.
Nops.

**Comment by bkrem** [comment]
Hi,

It's not clear to me what the behaviour for this requested feature would be.

Could you please link me to the relevant docs since you mentioned this is already natively supported by D3?

**Comment by bkrem** [comment]
You're already able to render multiple instances of the tree in a single page/DOM hierarchy, but this seems to be something more specific
