### ISSUE TITLE
Stop zoom behaviour on scroll

### ISSUE THREAD

**Issue by mprabs** [bkrem/react-d3-tree#352]
## Are you reporting a bug, or opening a feature request?
May be a feature or help with an implementation
  
## What is the actual behavior/output?
Right now when you scroll on the tree, the tree either zooms in or zooms out and you can also drag the tree to different positions. 

## What is the behavior/output you expect?
Is there a way that you can stop this zoom behavior on scroll but the drag feature remains there?

## What version of react-d3-tree are you using?
2.0.1

**Comment by bkrem** [comment]
Hi @mprabs,

Yes, this behaviour should've been possible already via the `zoomable` prop, but it needed some additionally work as expected post-v2 release. 

I've patched it in [v2.0.4](https://github.com/bkrem/react-d3-tree/releases/tag/v2.0.4) to work as expected: if `props.zoomable` is set to `false`, the tree can still be dragged but the scale/zoom remains constant at the level set by `props.zoom` (`1` by default).

As a workaround for prior versions, setting `props.scaleExtent` to a constant min/max (e.g. `scaleExtent={{min: 1, max: 1}}`) should achieve the same effect.

I've now also added a `Zoomable` switch in the [demo's controls](https://bkrem.github.io/react-d3-tree/) to make it easier to see both configuration states.

Hope that helps! 👍
