### ISSUE TITLE
Node Children

### ISSUE THREAD

**Issue by Emsu** [bkrem/react-d3-tree#36]
As a separate prop maybe called `children` it would be great to pass children into the `nodeSvgShape` to allow for SVG nodes that are more complex than a shape.

I may be able to get the implementation working but might need some help.

- [ ] Implementation
- [ ] Unit test
- [ ] Docs

**Comment by bkrem** [comment]
@Emsu In case this is still relevant for you, could you please check out v1.8.0's `nodeLabelComponent` feature to see if it meets your use case?

**Comment by Emsu** [comment]
hey @bkrem thanks! I'll check it out
