### ISSUE TITLE
Disable Drag

### ISSUE THREAD

**Issue by gouldie** [bkrem/react-d3-tree#364]
## Are you reporting a bug, or opening a feature request?
Feature request
  
## What is the actual behavior/output?
Unable to disable dragging since 2.0.4

We're currently trying to upgrade react-d3-tree in a project, but we'd like to be able to disable dragging of the tree. This was possible prior to v2.0.4 as setting `zoomable` to false also disabled the drag, but as far as I can tell since v2.0.4 there is no way to do this.

## What is the behavior/output you expect?
I'd like to be able to disable dragging of the tree

**Comment by Misil4** [comment]
same problem here, zoomable only disabled mouse wheel

**Comment by DanielLuu** [comment]
Any updates on this?

**Comment by jheaff1** [comment]
I too would like to be able to disable drag to just show a static tree

**Comment by msmfa** [comment]
Any plans to restore this feature? @bkrem

**Comment by bkrem** [comment]
Shipped as https://github.com/bkrem/react-d3-tree/releases/tag/v3.5.0 🚢 

I realise this was wanted so apologies for the wait. If I had realised this was as simple as it apparently was to restore it wouldn't have taken until now! 

Thank you again @gouldie for resolving this with a simple solution 💯

**Comment by jorgegarba** [comment]
I'm arriving a little bit late, does anybody know about the following bug? I think it is related to the issue or at least is similar

https://stackoverflow.com/questions/77272006/react-d3-tree-zoom-and-drag-not-working-on-next-js-13

**Comment by zdychacek** [comment]
Same here, using Next 14. Zooming and dragging not working. Any chance to be fixed?

**Comment by smsidki** [comment]
> Same here, using Next 14. Zooming and dragging not working. Any chance to be fixed?

it works if rendered on client side https://stackoverflow.com/a/78373583/6908415
