### ISSUE TITLE
Custom `pathFunc`

### ISSUE THREAD

**Issue by Emsu** [bkrem/react-d3-tree#37]
Besides elbow, diagonal, and straight, would be great to pass a custom func. My use case is an elbow like func with 4 segments instead of 2.

Looks like we can just add function as an acceptable propType in the enum and call the function if a function is given otherwise check for 'straight', 'diagonal', and 'elbow' as is currently done.

- [x] Implementation
- [x] Unit test
- [x] Docs

**Comment by bkrem** [comment]
Hey @Emsu,

Finally released this in [v1.5.1](https://github.com/bkrem/react-d3-tree/releases/tag/v1.5.1), so I'll be closing the issue.

Thank you for your contribution and keen to see what can be done about #36! :)
