### ISSUE TITLE
How can I add a custom path in a tree?

### ISSUE THREAD

**Issue by mprabs** [bkrem/react-d3-tree#387]
## Are you reporting a bug, or opening a feature request?
Feature Request
  
## What is the actual behavior/output?
Right now, I'm using the exact data structure (not the exact data though)
![image](https://user-images.githubusercontent.com/29838005/160551257-3bfee96a-7385-407c-9b9a-d2fd610cf9de.png)
as shown in the docs to render a tree that looks like this.
![image](https://user-images.githubusercontent.com/29838005/160551310-14d4ed3e-c906-4b98-8fef-6397cff2a907.png)

## What is the behavior/output you expect?
Is there a way so that I can show a new path connecting two new boxes like this without not disrupting the actual tree structure? Like this ![Screenshot 2022-03-29 123519](https://user-images.githubusercontent.com/29838005/160551634-e9a777f1-76ac-4584-876e-140a5ad5c10c.png)

Note: It will work even if the tree structure is disrupted. The main thing I want is to connect a box that is at a very high level to a box to a very low level.

## What version of react-d3-tree are you using?
react-d3-tree 2.0.1

**Comment by paulo-evangelista** [comment]
Hey! Got any updates? I'm in the same situation. Thanks

**Comment by mprabs** [comment]
@paulo-evangelista nope i didn't...i used another package 'reaflow' to overcome this.
