### ISSUE TITLE
Ensure support for React 16

### ISSUE THREAD

**Issue by bkrem** [bkrem/react-d3-tree#39]
- [ ] Implementation
- [ ] Unit test
- [ ] Docs

**Comment by jmorrice** [comment]
+1! Quite a few issues mainly related to paths since updating

**Comment by bkrem** [comment]
Ok, can you explain what's going on @jmorrice?

**Comment by bkrem** [comment]
Ok interesting. That would be great if you have a few minutes 👏 

Will push out a new version ASAP if you have a PR at some point, otherwise I'll investigate myself this evening.

**Comment by bkrem** [comment]
@jmorrice can't see any obvious issues after upgrading the demo to react/react-dom 16.x, could you please post the setup you're using the library in?

**Comment by jmorrice** [comment]
My mistake, turns out the problem was related to updating `react-transition-group` from `1.1.3` to `2.2.1`. So we can close this issue, but shall I open another ticket for updating that package?

**Comment by bkrem** [comment]
Ok, suspected that might have been the reason. 

Sure feel free to open an issue for an upgrade to transition-group v2. 

It should actually be declared as a peer dependency rather than a direct dependency anyways, as it can cause hard to track bugs this way. 
That’s a breaking change though so will have to wait until `react-d3-tree` v2. Refactoring and upgrading should hopefully be possible now though.
