### ISSUE TITLE
fix: allow react v 18 as peer dep

### ISSUE THREAD

**Issue by kelvin9314** [bkrem/react-d3-tree#397]
Thank you for taking the time to report an issue with react-d3-tree!  

Feel free to delete any questions that do not apply.

## Are you reporting a bug, or opening a feature request?
bug
  
## What is the actual behavior/output?
it show error while npm install

## What is the behavior/output you expect?
clear these the error while npm install

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?
no

## What version of react-d3-tree are you using?
3.3.2

## If react-d3-tree crashed with a traceback, please paste the full traceback below.
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x || 17.x" from react-d3-tree@3.3.2
npm ERR! node_modules/react-d3-tree
npm ERR!   react-d3-tree@"^3.3.2" from the root project

**Comment by bkrem** [comment]
Hi @kelvin9314,

Thanks for making me aware of this and the PR you added :+1: I've had zero time to work on issues for this package the last couple of weeks so I'm currently catching up.

I've tested the package against react 18 and now published the peerDep adjustment (https://github.com/bkrem/react-d3-tree/releases/tag/v3.3.4) and updated the demo, which now runs against react@18.2.0.

Let me know if you're still seeing issues with peer dependencies or any unexpected breakage with React 18 🙏

**Comment by kelvin9314** [comment]
> 

Thanks mate

**Comment by kelvin9314** [comment]
> Hi @kelvin9314,
> 
> Thanks for making me aware of this and the PR you added 👍 I've had zero time to work on issues for this package the last couple of weeks so I'm currently catching up.
> 
> I've tested the package against react 18 and now published the peerDep adjustment (https://github.com/bkrem/react-d3-tree/releases/tag/v3.3.4) and updated the demo, which now runs against react@18.2.0.
> 
> Let me know if you're still seeing issues with peer dependencies or any unexpected breakage with React 18 🙏

Thanks mate
