### ISSUE TITLE
Long render times for large datasets

### ISSUE THREAD

**Issue by tudorbertiean** [bkrem/react-d3-tree#41]
Is there any work around for the long rendering time for large datasets? I have approximately 500 nodes and the rendering freezes the page for about 1 minute until finally displayed.

Also occurs when using your data from 'json-example.json'.

**Comment by bkrem** [comment]
Hey @tudorbertiean,

Thanks for reminding me of this and apologies for the bottleneck. I'm currently working on a few performance improvements for large graphs to avoid blocking the main render thread for long periods of time.
Will hopefully have a release this evening that includes some improvements for your use case. 

Seen some significant speed ups with the JSON example you mentioned, would be great to have your tree to test with if it's not private/confidential info :)

**Comment by tudorbertiean** [comment]
Thanks for the response, I will attach the json file but modified the data for testing purposes.

Keep up the good work!

[https://github.com/bkrem/react-d3-tree/files/1398585/hierarchy.zip]

**Comment by bkrem** [comment]
Awesome, thank you for this! It's super useful to have a large dataset that approximates a real world use case for someone.

I'll be pushing a release tomorrow or Sunday at the latest that should improve performance a lot for large graphs 👍

**Comment by RohanDamani** [comment]
+1

I'm trying to render 10+ trees at once with different data sets and it crashes the browser

thanks for actively maintaining this project!!

**Comment by bkrem** [comment]
@RohanDamani Damn sorry about that, this should get a lot more stable this weekend.

**Comment by bkrem** [comment]
@tudorbertiean @RohanDamani 

Released this as v1.5.1 just now so closing the issue. Please check the [release notes](https://github.com/bkrem/react-d3-tree/releases/tag/v1.5.1), update and let me know in a new issue if something is wrong :)

The major bottleneck seems to lie with D3's `select().transition()` which blows up the browser's call stack whenever all the nodes in a large graph are mounted/unmounted at once (i.e. on initial load, collapsing to the root node).

I'll see what can be done to throttle/debounce the calls to still be able to use transitions on very large graphs while keeping responsiveness. Suggestions/contributions always welcome!

**Comment by RohanDamani** [comment]
@bkrem much better thanks!

**Comment by RohanDamani** [comment]
@bkrem much better thanks!

**Comment by jameerjbr** [comment]
Hey @bkrem 

I am using larger data tree render take more time and zoom also problem please fix it.
i will attached my code for testing purpose 
[tree.zip](https://github.com/bkrem/react-d3-tree/files/2591586/tree.zip)

**Comment by tsamawi** [comment]
Has this custom solution been implemented?

> @tudorbertiean @RohanDamani
> 
> Released this as v1.5.1 just now so closing the issue. Please check the [release notes](https://github.com/bkrem/react-d3-tree/releases/tag/v1.5.1), update and let me know in a new issue if something is wrong :)
> 
> The major bottleneck seems to lie with D3's `select().transition()` which blows up the browser's call stack whenever all the nodes in a large graph are mounted/unmounted at once (i.e. on initial load, collapsing to the root node).
> 
> I'll see what can be done to throttle/debounce the calls to still be able to use transitions on very large graphs while keeping responsiveness. Suggestions/contributions always welcome!

Has this been implemented?
