### ISSUE TITLE
Initial Depth 1 - Links not aligning with nodes

### ISSUE THREAD

**Issue by RohanDamani** [bkrem/react-d3-tree#42]
When initial depth one is set, the links are not aligned with the nodes.  The nodes are evenly spaced and the links are evenly spaced, however they do not have the same spacing.  Initial depth 0 and 2 working as expected.  Any ideas?  See pictures below:

`<Tree data={[data]} translate={{x: 300, y:300}} initialDepth={1} styles={{links: {stroke: 'pink', strokeWidth: 3}}} />`

![image](https://user-images.githubusercontent.com/8662419/31909969-c55a626e-b7f0-11e7-835b-2eb88b662ef8.png)

**Comment by bkrem** [comment]
Hey @RohanDamani,

Thanks for adding your `<Tree />` config, not sure about this exact scenario but I think I know what this is. 

Noticed after releasing the update optimisations in 1.5.1 that the nodes aren't aware of some top level prop changes that actually reflow the layout.

Sorry about this, releasing a fix tomorrow evening which should hopefully solve it, along with some way nicer coordinated transitions which keep large graphs responsive while rendering. 

Will keep you updated!

**Comment by bkrem** [comment]
@RohanDamani 

Fixed in [v1.5.2](https://github.com/bkrem/react-d3-tree/releases/tag/v1.5.2).

Not happy yet with the coordinated transitions so 1.6.0 will be a bit longer, until then I'd still recommend to set `transitionDuration: 0` for large graphs for max responsiveness 🚀

**Comment by RohanDamani** [comment]
@bkrem Great fixed thanks!
