### ISSUE TITLE
Link to "TreeProps reference docs."

### ISSUE THREAD

**Issue by Momen-Mawad** [bkrem/react-d3-tree#427]
The following link is not working:
https://bkrem.github.io/react-d3-tree/docs/interfaces/_tree_types_.treeprops.html

It is mentioned in the README of the repository here:
https://github.com/bkrem/react-d3-tree#:~:text=check%20out%20the-,TreeProps%20reference%20docs.,-The%20only%20required

**Comment by bkrem** [comment]
Thanks for making me aware 🙏 all references in the readme should be fixed now. 

Looks like the slight change to support ESM in the build chain created a breaking change in the URL paths generated by Typedoc.

**Comment by FrankSFLYS** [comment]
Still 404, any permlinks to the doc?
