### ISSUE TITLE
Add svg text transform functionality to Node names

### ISSUE THREAD

**Issue by alexlamasBV** [bkrem/react-d3-tree#44]
Include the SVG transform attribute as a prop to a Node's textLayout. I gave a simple implementation a shot in [this PR](https://github.com/bkrem/react-d3-tree/pull/43).

One use case: rotate Node names, such that longer names don't overlap with Nodes at the next level of the Tree.

<img width="345" alt="react-d3-tree" src="https://user-images.githubusercontent.com/29458513/32026730-2ba219f2-b9ab-11e7-89e6-3fc6ddfea530.png">

**Comment by bkrem** [comment]
@alexlamasBV 

Released in v1.6.0, release notes: https://github.com/bkrem/react-d3-tree/releases/tag/v1.6.0

Thanks again for implementing this! ✨
