### ISSUE TITLE
Question: How do you import type `TreeProps`?

### ISSUE THREAD

**Issue by remarkablemark** [bkrem/react-d3-tree#440]
## Are you reporting a bug, or opening a feature request?

TypeScript question
  
## What is the actual behavior/output?

Importing type throws error:

<img width="817" alt="Screen Shot 2023-02-05 at 5 25 03 PM" src="https://user-images.githubusercontent.com/10594555/216849513-2c5872e6-f2f4-493b-9617-8283750d481e.png">

I ended up having to import the type with:

```ts
import { TreeProps } from 'react-d3-tree/lib/types/Tree/types'
```

## What is the behavior/output you expect?

Importing type should work:

```ts
import type { TreeProps } from 'react-d3-tree'
```

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?

https://replit.com/@remarkablemark/react-d3-tree#src/CenteredTree.tsx

## What version of react-d3-tree are you using?

3.5.0

## If react-d3-tree crashed with a traceback, please paste the full traceback below.

N/A

**Comment by devam-Scaletech** [comment]
@remarkablemark  
try to import like this :arrow_down_small: 
import { TreeProps } from 'react-d3-tree/lib/Tree/types';

**Comment by Devamchaudhari** [comment]
@remarkablemark  
try to import like this :arrow_down_small: 
import { TreeProps } from 'react-d3-tree/lib/Tree/types';

**Comment by remarkablemark** [comment]
Thanks @Devamchaudhari!

**Comment by Devamchaudhari** [comment]
> Thanks @Devamchaudhari!

Welcome @remarkablemark  :smile:
