### ISSUE TITLE
draggable prop not working on mobile

### ISSUE THREAD

**Issue by dungle-groove** [bkrem/react-d3-tree#444]
Thank you for taking the time to report an issue with react-d3-tree!  

Feel free to delete any questions that do not apply.

## Are you reporting a bug, or opening a feature request?
Report a bug
  
## What is the actual behavior/output?
I have set **draggable = false** but it only worked for desktop, not on touch devices. Because mobile only triggers **touchmove** instead **mousemove** event therefore this condition cannot be caught.
![image](https://user-images.githubusercontent.com/63702692/221895708-5ea80e45-0e8b-4c37-9f55-111d7976c589.png)

## What version of react-d3-tree are you using?
"react-d3-tree": "3.5.0"

**Comment by bkrem** [comment]
Thanks for raising this 🙏 

Fixed by @Adeams1805 in #448.

Patched in https://github.com/bkrem/react-d3-tree/releases/tag/v3.5.1
