### ISSUE TITLE
Provide ability to import Tree types.

### ISSUE THREAD

**Issue by MaxArnaut** [bkrem/react-d3-tree#454]
## What is the actual behavior/output?
Can't import any types from your package

## What is the behavior/output you expect?
Please provide ability to import types need it to be able to split the code to different files.

## What version of react-d3-tree are you using?
[v3.51]

**Comment by bkrem** [comment]
Fixed via https://github.com/bkrem/react-d3-tree/releases/tag/v3.5.2
