### ISSUE TITLE
onHover feature request

### ISSUE THREAD

**Issue by RohanDamani** [bkrem/react-d3-tree#48]
I'd like to display a popover or snackbar onHover of each node.  Requesting an onHover prop which passes the node data to a function on user hover.

**Comment by bkrem** [comment]
Hey @RohanDamani,

I  think this would be a good first-time contribution for you if you're up for it :) 

Pretty much the same logic as is already there for the `onClick` prop.

**Comment by RohanDamani** [comment]
https://github.com/bkrem/react-d3-tree/pull/50

see comments, not sure how to test

**Comment by bkrem** [comment]
Released in [v1.7.0](https://github.com/bkrem/react-d3-tree/releases/tag/v1.7.0)
