### ISSUE TITLE
Codesandbox examples not available

### ISSUE THREAD

**Issue by mrtnbrst** [bkrem/react-d3-tree#500]
Codesandbox links from README in section https://github.com/bkrem/react-d3-tree?tab=readme-ov-file#rendercustomnodeelement are not working.

## Are you reporting a bug, or opening a feature request?
Bug
  
## What is the actual behavior/output?
Examples are not available.

## What is the behavior/output you expect?
Examples should be available.

**Comment by bkrem** [comment]
@mrtnbrst I just tried to access all codesandbox.io links in that section in incognito and they seem to come up fine. What exactly is the issue you're seeing?

**Comment by mrtnbrst** [comment]
@bkrem Yes, now they work again. I don't know what was the issue back then but now it works for both you and me.

Thanks :)
