### ISSUE TITLE
onClick change style

### ISSUE THREAD

**Issue by krunal039** [bkrem/react-d3-tree#51]
sorry if this is alreay covered but could not find way to change style for selected node and reset for unselected node.

**Comment by bkrem** [comment]
Hi @krunal039,

Thanks for your suggestion! You're right, there's currently no direct way to style the currently active/focused node.

I'll have a think of how this can be best implemented. In the meantime, feel free to share your thoughts on how you'd implement this :)

**Comment by krunal039** [comment]
@bkrem thanks for quick reply, I do not have any specific but it would be good if selected node/label has different color, there could be props at component level for selectedCss? I would prefer that componet just add data attribute for selected component and then user can apply any css they want. Also on that note, is there way to auto size node tree on load?

**Comment by bkrem** [comment]
Yeah agreed, having simple data attributes to hook into with CSS (+ a way to style the active node via props) would be good 👍 

Unsure of what exactly you mean with "auto-size", feel free to email me (ben.kremer@hotmail.co.uk) or open another issue with a description of your problem and I'll do my best to help!

**Comment by recaorshell** [comment]
Hello @bkrem Could you please let me know how to apply this question?
When I select the node, not sure how to change the selected node's style.
Please give me the answer.
Thank you
