### ISSUE TITLE
can't find variable document 

### ISSUE THREAD

**Issue by issamabdelkrim** [bkrem/react-d3-tree#74]
![capture d ecran 2018-01-30 a 22 56 29](https://user-images.githubusercontent.com/11806926/35593685-dd3ec942-0610-11e8-8d1b-6c42e13aa07a.png)
when i do import Tree from 'react-d3-tree';
can someone help me plz 
thanks

**Comment by bkrem** [comment]
Hey @issamabdelkrim,

Looks like you're trying to use the library in a React Native context, which isn't possible since there's [no DOM within React Native](https://github.com/facebook/react-native/issues/838). 
So the error is actually correct since this is a library for web-based React.

**Comment by issamabdelkrim** [comment]
thanks @bkrem for your answer
