### ISSUE TITLE
Get events on mouse's callbacks

### ISSUE THREAD

**Issue by j-barata** [bkrem/react-d3-tree#88]
I can't find any way to retrieve the event occured when "onClick" or "onMouseOver" or "onMouseOut".

I think this could be done in the rendering method of the Node object ?

Something like that : `<g ... onClick={(event) => this.handleClick()} ...`

What is your opinion ?

**Comment by bkrem** [comment]
Good point, I'm actually surprised this hasn't come up as a request until now and that I didn't consider forwarding the event up the call chain (as would be done in most cases).

Thank you for bringing this to my attention! Adding it as a prio ticket for the next release.

**Comment by bkrem** [comment]
Shipped in [v1.10.2](https://github.com/bkrem/react-d3-tree/releases/tag/v1.10.2) 🚀

**Comment by j-barata** [comment]
thank you very much for being so fast
