### ISSUE TITLE
react-transition-group causes unnecessary slowdown when animations are disabled

### ISSUE THREAD

**Issue by sspanak** [bkrem/react-d3-tree#91]
Hi,

I've been experimenting with large trees, consisting of 2000 or more, and I've noticed 
performance is so bad that the entire page becomes unusable.

I have investigated the issue and found the culprit - it is react-transition-group. From what I understand it is only required when animations are enabled, and since I don't need them, I tried removing it. After that I have conducted some tests and the results are significantly faster rendering time, as well as much more responsive graph, even if there are many nodes.

Here are some numbers:

With react-transition-group
---
Nodes: 309, Links: 308
Tree render time: 1767 ms

Nodes: 609, Links: 608
Tree render time: 5575 ms

Nodes: 1216, Links: 1215
Tree render time: 20966 ms

Nodes: 2432, Links: 2431
Tree render time: 75553 ms

With a plain `<g>` element
---
Nodes: 309, Links: 308
Tree render time: 671 ms

Nodes: 609, Links: 608
Tree render time: 1431ms

Nodes: 1216, Links: 1215
Tree render time: 2722 ms

Nodes: 2432, Links: 2431
Tree render time: 5270 ms

Nodes: 4862, Links: 4861
Tree render time: 10731 ms

So, @bkrem , correct me if I am wrong, but I think react-transition-group can be removed when animations are disabled (transitionDuration=0). I can prepare a pull request for the issue.

**Comment by sspanak** [comment]
OK, so I have opened pull request #92, to address the issue. @bkrem, I would appreciate if you review and consider the changes, when you have some spare time.

**Comment by bkrem** [comment]
Hey @sspanak,

Thanks for for investigating this properly! `transitionDuration = 0` helped a lot with render times on smaller graphs but I hadn't yet properly benchmarked how  behaves on large graphs.

Will review your PR now and push out a release with your improvement if we're all good.

**Comment by bkrem** [comment]
Released as [v1.10.3](https://github.com/bkrem/react-d3-tree/releases/tag/v1.10.3) 🚀 

Thank you again for your awesome contributions @sspanak!
