### ISSUE TITLE
not able to zoom if multiple trees are present.

### ISSUE THREAD

**Issue by nimitwalia89** [bkrem/react-d3-tree#93]
If we have multiple tree each wrapped in its own div then only 1st tree is zoomable. 
`<div>`
`<Tree ...props />`
`</div>`
`<div>`
`<Tree ...props />`
`</div>`
`<div>`
`<Tree ...props />`
`</div>`
Only first tree will be zoomable here.

**Comment by bkrem** [comment]
Fixed in [v1.10.5](https://github.com/bkrem/react-d3-tree/releases/tag/v1.10.5) 🎉
