### ISSUE TITLE
initialDepth broken in version 1.10.4 

### ISSUE THREAD

**Issue by juanda99** [bkrem/react-d3-tree#99]
New to react-d3-tree, so just test it, see repo:
https://codesandbox.io/s/r15w64jqym

My repo works ok with version 1.4, but not with 1.9 or 1.10 version
Do I miss something? Any breaking change?

**Comment by bkrem** [comment]
Fixed in [v1.10.6](https://github.com/bkrem/react-d3-tree/releases/tag/v1.10.6) 🚀
